# fly.toml app configuration file para betsapi-floral-rain-1393

app = 'betsapi-floral-rain-1393'
primary_region = 'gig'

# Configuração simplificada apenas para backfill
[processes]
app = "python main.py --mode backfill --workers 4"

# Desativar a criação de máquinas standby
[deploy]
strategy = "immediate"

[experimental]
enable_machines = true
auto_rollback = false

# VM para backfill
[[vm]]
cpu_kind = "performance"
cpus = 4
memory = "8192mb"
processes = ["app"]
