# fly.toml app configuration file para betsapi-floral-rain-1393

app = "betsapi-floral-rain-1393"
primary_region = "gig"

# Configuração para manter o cron como processo principal
[processes]
app = "cron -f"  # Mantém o cron rodando em foreground como processo principal

# Desativar a criação de máquinas standby
[deploy]
strategy = "immediate"

# VM para processamento agendado
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1024mb"
processes = ["app"]

[env]
PORT = "8080"

# Configuração mínima do servidor HTTP para satisfazer os requisitos do Fly.io
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

# Configuração da porta necessária (exigência do Fly.io)
[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
