# fly.toml app configuration file para betsapi-floral-rain-1393

app = "betsapi-floral-rain-1393"
primary_region = "gig"

# Configuração simplificada apenas para backfill
[processes]
app = "python main.py --mode update-scores"  # Executa uma única vez na inicialização
cron = "cron -f"  # Mantém o cron rodando em foreground

# Desativar a criação de máquinas standby
[deploy]
strategy = "immediate"
release_command = "./scripts/setup_cron.sh"

[experimental]
cmd = ["python", "main.py", "--mode", "backfill", "--workers", "4"]
memory = "8192mb"
processes = ["app"]

# VM para backfill
[[vm]]
cpu_kind = "performance"
cpus = 4
memory = "8192mb"
processes = ["app"]

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

# Executa o cron como um serviço em segundo plano
[[services]]
http_checks = []
internal_port = 8080
processes = ["cron"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
