# fly.toml app configuration file
app = "betsapi-floral-rain-1393"
primary_region = "gig"

# Configuração de processo: apenas o cron em foreground
[processes]
app = "cron -f"

# Configuração básica de deploy
[deploy]
strategy = "immediate"

# VM para processamento agendado
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1024mb"
processes = ["app"]
