# fly.toml app configuration file para betsapi-floral-rain-1393

app = "betsapi-floral-rain-1393"
primary_region = "gig"

# Configuração para manter o cron como processo principal
[processes]
app = "cron -f"  # Mantém o cron rodando em foreground como processo principal

# Desativar a criação de máquinas standby
[deploy]
strategy = "immediate"

# VM para processamento agendado
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1024mb"
processes = ["app"]

[env]
PORT = "8080"

# Servidor HTTP para manter a VM viva
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

# Executa o cron como um serviço em segundo plano
[[services]]
http_checks = []
internal_port = 8080
processes = ["cron"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
