[tool.poetry]
name = "betsapi"
version = "0.1.0"
description = ""
authors = ["Yure Araujo dos Santos <yureesantos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
